name: GitHub metrics
on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches: "master"
jobs:
  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:

      - name: Personal metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "header, repositories"
          plugin_lines: yes
          plugin_music: yes
          plugin_music_playlist: ${{ secrets.MUSIC_PLAYLIST }}
          plugin_music_limit: 2
          plugin_isocalendar: yes
          plugin_topics: yes
          plugin_topics_mode: mastered
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_facts: no
          plugin_habits_charts: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot
          plugin_languages_skipped: lowlighter
          plugins_errors_fatal: yes
          config_timezone: Europe/Paris
          
      - name: Personal metrics (additional)
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.additional.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "metadata"
          plugin_stargazers: yes
          plugin_stars: yes
          plugin_stars_limit: 3
          
      - name: Personal projects
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.projects.svg
          token: ${{ secrets.METRICS_BOT_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: lowlighter
          base: ""
          plugin_projects: yes
          plugin_projects_repositories: lowlighter/metrics/projects/1
          plugin_projects_limit: 0
          config_timezone: Europe/Paris


  github-metrics:
    needs: [github-metrics-personal]
    runs-on: ubuntu-latest
    if: "github.repository == 'katvin/Katvin'"
    steps:

      # Classic template with header and repositories sections
      - name: Classic template
        uses: lowlighter/metrics@master
        with:
          filename: metrics.classic.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "header, repositories"
          plugin_lines: yes
          plugins_errors_fatal: yes
          config_timezone: Europe/Paris
          use_prebuilt_image: master

      # Terminal template with header and metadata sections
      - name: Terminal template
        uses: lowlighter/metrics@master
        with:
          template: terminal
          filename: metrics.terminal.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "header, metadata"
          plugins_errors_fatal: yes
          config_timezone: Europe/Paris
          use_prebuilt_image: master

      # Repository template
      # Displays header section along with ratio of open/closed/merged issues and pull requests and active projects
      # Note that : 
      # - As projects requires "public_repo" scope, you can use a bot account instead and use the "user" option instead
      # - You must pass the additional query parameter "repo" in a JSON format
      - name: Repository template
        uses: lowlighter/metrics@master
        with:
          template: repository
          filename: metrics.repository.svg
          token: ${{ secrets.METRICS_BOT_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: lowlighter
          query: '{"repo":"metrics"}'
          plugin_lines: yes
          plugin_followup: yes
          plugin_projects: yes
          plugin_projects_repositories: lowlighter/metrics/projects/1
          plugins_errors_fatal: yes
          config_timezone: Europe/Paris
          use_prebuilt_image: master

      # Google PageSpeed insight audits
      # Don't forget to update your GitHub profile with your website
      # Token is optional but advised
      - name: PageSpeed plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.pagespeed.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_pagespeed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugins_errors_fatal: yes
          config_timezone: Europe/Paris
          use_prebuilt_image: master

      # Google PageSpeed insight audits, with additional performance metrics displayed
      # Don't forget to update your GitHub profile with your website
      # Token is optional but advised
      - name: PageSpeed plugin (detailed)
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.pagespeed.detailed.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugins_errors_fatal: yes
          config_timezone: Europe/Paris
          use_prebuilt_image: master

      # Google PageSpeed insight audits, with an additional screenshot of your website
      # Don't forget to update your GitHub profile with your website
      # Token is optional but advised
      - name: PageSpeed plugin (screenshot)
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.pagespeed.screenshot.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_pagespeed: yes
          plugin_pagespeed_screenshot: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugins_errors_fatal: yes
          config_timezone: Europe/Paris
          use_prebuilt_image: master

      # Display random tracks from the given embed playlist
      # Note that :  
      # - "plugin_music_mode" and "plugin_music_provider" are both optional (they're deduced from "plugin_music_playlist")
      # - "plugin_music_token" is not needed as it uses pupeeter to retrieve tracks
      - name: Music plugin (playlist)
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.music.playlist.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_music: yes
          plugin_music_playlist: ${{ secrets.MUSIC_PLAYLIST }}
          plugin_music_limit: 2
          plugins_errors_fatal: yes
          config_timezone: Europe/Paris
          use_prebuilt_image: master

      # Display recently played music
      # Note that :
      # - "plugin_music_mode", "plugin_music_provider" and "plugin_music_token" are all required
      - name: Music plugin (recent)
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.music.recent.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_mode: recent
          plugin_music_token: ${{ secrets.SPOTIFY_TOKENS }}
          plugin_music_limit: 2
          plugins_errors_fatal: yes
          config_timezone: Europe/Paris
          use_prebuilt_image: master

      # Display coding habits and recent activity
      # Don't forget to setup timezone for accurate metrics
      - name: Habits plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.habits.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugins_errors_fatal: yes
          config_timezone: Europe/Paris
          use_prebuilt_image: master

      # Display coding habits and recent activity (only facts section)
      # Don't forget to setup timezone for accurate metrics
      - name: Habits plugin (facts)
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.habits.facts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no
          plugins_errors_fatal: yes
          config_timezone: Europe/Paris
          use_prebuilt_image: master

      # Display coding habits and recent activity (only charts section)
      # Don't forget to setup timezone for accurate metrics
      - name: Habits plugin (charts)
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.habits.charts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          plugins_errors_fatal: yes
          config_timezone: Europe/Paris
          use_prebuilt_image: master

      # Display most used languages
      # You can ignore some languages and skip some repositories if you want
      - name: Languages plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot
          plugin_languages_skipped: lowlighter
          plugins_errors_fatal: yes
          config_timezone: Europe/Paris
          use_prebuilt_image: master

      # Display ratio of open/closed/merged issues and pull requests 
      - name: Follow-up plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.followup.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_followup: yes
          plugins_errors_fatal: yes
          config_timezone: Europe/Paris
          use_prebuilt_image: master

      # Display number of line changed
      # Note that :
      # - This is part of "repositories" section, so you need to enable it
      - name: Lines plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.lines.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "repositories"
          plugin_lines: yes
          plugins_errors_fatal: yes
          config_timezone: Europe/Paris
          use_prebuilt_image: master

      # Display number of repositories views
      # Note that :
      # - This is part of "repositories" section, so you need to enable it
      # - A "repo" scope is required
      - name: Traffic plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.traffic.svg
          token: ${{ secrets.METRICS_BOT_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "repositories"
          plugin_traffic: yes
          plugins_errors_fatal: yes
          config_timezone: Europe/Paris
          use_prebuilt_image: master

      # Display recent posts
      # Note that : 
      # - "plugin_posts_source" is required
      # - With "dev.to" as source, your GitHub username is directly used
      - name: Posts plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.posts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_posts: yes
          plugin_posts_source: dev.to
          plugins_errors_fatal: yes
          config_timezone: Europe/Paris
          use_prebuilt_image: master

      # Display isometric calendar (180 days)
      - name: Isocalendar plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugins_errors_fatal: yes
          config_timezone: Europe/Paris
          use_prebuilt_image: master

      # Display isometric calendar (365 days)
      - name: Isocalendar plugin (full year)
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugins_errors_fatal: yes
          config_timezone: Europe/Paris
          use_prebuilt_image: master

      # Display gists metrics
      - name: Gists plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.gists.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_gists: yes
          plugins_errors_fatal: yes
          config_timezone: Europe/Paris
          use_prebuilt_image: master

      # Display starred topics (as labels)
      - name: Topics plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.topics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 12
          plugins_errors_fatal: yes
          config_timezone: Europe/Paris
          use_prebuilt_image: master

      - name: Topics plugin (mastered)
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.topics.mastered.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_topics: yes
          plugin_topics_mode: mastered
          plugins_errors_fatal: yes
          config_timezone: Europe/Paris
          use_prebuilt_image: master


      - name: Projects plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.projects.svg
          token: ${{ secrets.METRICS_BOT_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_projects: yes
          plugin_projects_repositories: lowlighter/metrics/projects/1
          plugins_errors_fatal: yes
          config_timezone: Europe/Paris
          use_prebuilt_image: master

      # Display your latest tweets
      # Don't forget to update your GitHub profile with your twitter username
      # Note that : 
      # - You must provide a "plugin_tweets_token"
      - name: Tweets plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.tweets.svg
          token: ${{ secrets.METRICS_BOT_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_tweets: yes
          plugin_tweets_token: ${{ secrets.TWITTER_TOKEN }}
          plugins_errors_fatal: yes
          config_timezone: Europe/Paris
          use_prebuilt_image: master
          
      # Display your stargazers evolutions
      - name: Stargazers plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.stargazers.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_stargazers: yes
          plugins_errors_fatal: yes
          config_timezone: Europe/Paris
          use_prebuilt_image: master
          
      # Display your latest starred repositories
      - name: Stars plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.stars.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_stars: yes
          plugin_stars_limit: 2
          plugins_errors_fatal: yes
          config_timezone: Europe/Paris
          use_prebuilt_image: master

      # This is used to illustrate special features with the use of "debug_flags"
      # - "--cakeday" will act as if it's your account birthday
      # - "--hireable" will act as if "Available for hire" is enabled on your account
      # - "--halloween" will act as if it was halloween, changing the colors of contributions calendar and isocalendar
      - name: Header (additional features)
        uses: lowlighter/metrics@master
        with:
          filename: metrics.header.svg
          token: ${{ secrets.METRICS_BOT_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "header"
          debug_flags: --cakeday --hireable --halloween
          plugins_errors_fatal: yes
          config_timezone: Europe/Paris
          use_prebuilt_image: master

      # This is used to illustrate plugin errors : 
      # The "METRICS_TOKEN" does not contains the "public_repo" scope, which is required for "plugin_projects"
      # It will display an "Insufficient token rights" error
      - name: Plugin error example
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.error.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_projects: yes
          plugins_errors_fatal: no
          config_timezone: Europe/Paris
          use_prebuilt_image: master
